/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ViewEmprestimos;

import view.ViewAcervo.*;
import dao.ItemDAO;
import dao.LoanDAO;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.Item;
import model.Loan;

/**
 *
 * @author Pedro Santos
 */
public class ViewPesquisarEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCadUsuarios
     */
    public ViewPesquisarEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmprestimo = new javax.swing.JTable();
        pesquisaInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbIdEmprestimo = new javax.swing.JRadioButton();
        rbIdItem = new javax.swing.JRadioButton();
        pesquisarBtn = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pesquisar Empréstimo");
        setMinimumSize(new java.awt.Dimension(1280, 695));
        setPreferredSize(new java.awt.Dimension(1280, 695));

        tableEmprestimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Cliente", "CPF do Cliente", "Cód. Item", "Título do Item", "Data do Empréstimo", "Data de Devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEmprestimo.setCellSelectionEnabled(true);
        tableEmprestimo.setRowHeight(40);
        jScrollPane2.setViewportView(tableEmprestimo);

        pesquisaInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisar por:");

        buttonGroup1.add(rbIdEmprestimo);
        rbIdEmprestimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbIdEmprestimo.setSelected(true);
        rbIdEmprestimo.setText("Cód. Empréstimo");
        rbIdEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIdEmprestimoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbIdItem);
        rbIdItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbIdItem.setText("Cód. Item");

        pesquisarBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pesquisarBtn.setText("Pesquisar");
        pesquisarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(pesquisarBtn)
                            .addComponent(pesquisaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(rbIdEmprestimo)
                        .addGap(18, 18, 18)
                        .addComponent(rbIdItem)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(pesquisaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIdEmprestimo)
                    .addComponent(rbIdItem)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(pesquisarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisarBtnActionPerformed
        String sql;
        DefaultTableModel table = (DefaultTableModel) tableEmprestimo.getModel();
        table.setNumRows(0);
        LoanDAO dao;

        if (rbIdItem.isSelected()) {
            sql = "SELECT cliente.nome, cliente.cpf, acervo.id, acervo.titulo, emprestimo.data_emprestimo, emprestimo.data_devolucao from emprestimo inner join cliente on emprestimo.id_cliente=cliente.id inner join acervo on emprestimo.id_acervo=acervo.id where acervo.id="
                    + pesquisaInput.getText();
        } else {
            sql = "SELECT cliente.nome, cliente.cpf, acervo.id, acervo.titulo, emprestimo.data_emprestimo, emprestimo.data_devolucao from emprestimo inner join cliente on emprestimo.id_cliente=cliente.id inner join acervo on emprestimo.id_acervo=acervo.id where emprestimo.id="
                    + pesquisaInput.getText();
        }

        try {
            dao = new LoanDAO();
            Object[] joinTable = dao.getJoinTable(sql);
            if (joinTable != null) {
                table.addRow(joinTable);
            } else {
                JOptionPane.showMessageDialog(null, "Empréstimo não encontrado");
            }
            dao.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }// GEN-LAST:event_pesquisarBtnActionPerformed

    private void rbIdEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbIdEmprestimoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbIdEmprestimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pesquisaInput;
    private javax.swing.JButton pesquisarBtn;
    private javax.swing.JRadioButton rbIdEmprestimo;
    private javax.swing.JRadioButton rbIdItem;
    private javax.swing.JTable tableEmprestimo;
    // End of variables declaration//GEN-END:variables
}
