/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ViewEmprestimos;

import view.ViewAcervo.*;
import dao.ItemDAO;
import dao.LoanDAO;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.Item;

/**
 *
 * @author Pedro Santos
 */
public class ViewEstenderEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCadUsuarios
     */
    public ViewEstenderEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        estenderEmprestimoBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmprestimo = new javax.swing.JTable();
        pesquisaInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbIdEmprestimo = new javax.swing.JRadioButton();
        rbIdItem = new javax.swing.JRadioButton();
        pesquisarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        novaDataInput = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Estender Empréstimo");
        setMinimumSize(new java.awt.Dimension(1280, 695));
        setPreferredSize(new java.awt.Dimension(1280, 695));

        estenderEmprestimoBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        estenderEmprestimoBtn.setText("Estender Empréstimo");
        estenderEmprestimoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estenderEmprestimoBtnActionPerformed(evt);
            }
        });

        tableEmprestimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Nome do Cliente", "CPF do Cliente", "Cód. Item", "Título do Item", "Data do Empréstimo",
                        "Data de Devolução"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tableEmprestimo.setCellSelectionEnabled(true);
        tableEmprestimo.setRowHeight(40);
        jScrollPane2.setViewportView(tableEmprestimo);

        pesquisaInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisar por:");

        buttonGroup1.add(rbIdEmprestimo);
        rbIdEmprestimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbIdEmprestimo.setSelected(true);
        rbIdEmprestimo.setText("Cód. Empréstimo");
        rbIdEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIdEmprestimoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbIdItem);
        rbIdItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbIdItem.setText("Cód. Item");

        pesquisarBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pesquisarBtn.setText("Pesquisar");
        pesquisarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Nova data de devolução:");

        novaDataInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(387, 387, 387)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(16, 16, 16)
                                                                .addComponent(novaDataInput,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(pesquisaInput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(386, 386, 386)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbIdEmprestimo)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbIdItem))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(548, 548, 548)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(estenderEmprestimoBtn)
                                                        .addComponent(pesquisarBtn))))
                                .addContainerGap(381, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(pesquisaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbIdEmprestimo)
                                        .addComponent(rbIdItem)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(pesquisarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(novaDataInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addComponent(estenderEmprestimoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(97, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estenderEmprestimoBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estenderEmprestimoBtnActionPerformed
        LoanDAO dao;
        String novaData = novaDataInput.getText();
        int id_item = Integer.parseInt(tableEmprestimo.getValueAt(0, 2).toString());

        try {
            dao = new LoanDAO();
            if (dao.updateDateDevolutionLoan(id_item, novaData)) {
                JOptionPane.showMessageDialog(null, "Empréstimo estendido!");
            } else {
                JOptionPane.showMessageDialog(null, "Erro! Tente novamente!");
            }

            dao.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }// GEN-LAST:event_estenderEmprestimoBtnActionPerformed

    private void pesquisarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisarBtnActionPerformed
        String sql;
        DefaultTableModel table = (DefaultTableModel) tableEmprestimo.getModel();
        table.setNumRows(0);
        LoanDAO dao;

        if (rbIdItem.isSelected()) {
            sql = "SELECT cliente.nome, cliente.cpf, acervo.id, acervo.titulo, emprestimo.data_emprestimo, emprestimo.data_devolucao from emprestimo inner join cliente on emprestimo.id_cliente=cliente.id inner join acervo on emprestimo.id_acervo=acervo.id where acervo.id="
                    + pesquisaInput.getText();
        } else {
            sql = "SELECT cliente.nome, cliente.cpf, acervo.id, acervo.titulo, emprestimo.data_emprestimo, emprestimo.data_devolucao from emprestimo inner join cliente on emprestimo.id_cliente=cliente.id inner join acervo on emprestimo.id_acervo=acervo.id where acervo.id="
                    + pesquisaInput.getText();
        }

        try {
            dao = new LoanDAO();
            Object[] joinTable = dao.getJoinTable(sql);
            table.addRow(joinTable);
            dao.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }// GEN-LAST:event_pesquisarBtnActionPerformed

    private void rbIdEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbIdEmprestimoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbIdEmprestimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton estenderEmprestimoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField novaDataInput;
    private javax.swing.JTextField pesquisaInput;
    private javax.swing.JButton pesquisarBtn;
    private javax.swing.JRadioButton rbIdEmprestimo;
    private javax.swing.JRadioButton rbIdItem;
    private javax.swing.JTable tableEmprestimo;
    // End of variables declaration//GEN-END:variables
}
