/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ViewEmprestimos;

import view.ViewAcervo.*;
import dao.ItemDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Item;

/**
 *
 * @author Pedro Santos
 */
public class ViewNovoEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCadUsuarios
     */
    public ViewNovoEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisarIdItemBtn = new javax.swing.JButton();
        IdItemInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        realizarEmprestimoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cpfClienteInput = new javax.swing.JTextField();
        pesquisarCpfBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItem = new javax.swing.JTable();

        setClosable(true);
        setTitle("Novo Empréstimo");
        setMinimumSize(new java.awt.Dimension(900, 434));
        setPreferredSize(new java.awt.Dimension(900, 434));

        pesquisarIdItemBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pesquisarIdItemBtn.setText("Pesquisar");
        pesquisarIdItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarIdItemBtnActionPerformed(evt);
            }
        });

        IdItemInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("ID do item:");

        realizarEmprestimoBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        realizarEmprestimoBtn.setText("Realizar Empréstimo");
        realizarEmprestimoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarEmprestimoBtnActionPerformed(evt);
            }
        });

        tableCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Email", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCliente);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("CPF do cliente:");

        cpfClienteInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        pesquisarCpfBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pesquisarCpfBtn.setText("Pesquisar");
        pesquisarCpfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarCpfBtnActionPerformed(evt);
            }
        });

        tableItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Teste", "Teste", "Teste", null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Editora", "Categoria", "Descrição", "Ano de publicação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(IdItemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfClienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realizarEmprestimoBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisarCpfBtn)
                    .addComponent(pesquisarIdItemBtn))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IdItemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarIdItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfClienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarCpfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(realizarEmprestimoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarCpfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarCpfBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarCpfBtnActionPerformed

    private void pesquisarIdItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarIdItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarIdItemBtnActionPerformed

    private void realizarEmprestimoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarEmprestimoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarEmprestimoBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdItemInput;
    private javax.swing.JTextField cpfClienteInput;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pesquisarCpfBtn;
    private javax.swing.JButton pesquisarIdItemBtn;
    private javax.swing.JButton realizarEmprestimoBtn;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableItem;
    // End of variables declaration//GEN-END:variables
}
