/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ViewEmprestimos;

import view.ViewAcervo.*;
import dao.ItemDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Item;

/**
 *
 * @author Pedro Santos
 */
public class ViewPesquisarAcervo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewListarUsuarios
     */
    public ViewPesquisarAcervo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisaOpcoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pesquisaInput = new javax.swing.JTextField();
        rbAutor = new javax.swing.JRadioButton();
        rbId = new javax.swing.JRadioButton();
        rbTitulo = new javax.swing.JRadioButton();
        rbEditora = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbCategoria = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItens = new javax.swing.JTable();
        pesquisarBtn = new javax.swing.JButton();
        mostrarDisponiveis = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Pesquisar Itens");

        pesquisaInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        pesquisaOpcoes.add(rbAutor);
        rbAutor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbAutor.setText("Autor");

        pesquisaOpcoes.add(rbId);
        rbId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbId.setSelected(true);
        rbId.setText("ID");

        pesquisaOpcoes.add(rbTitulo);
        rbTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbTitulo.setText("Título");

        pesquisaOpcoes.add(rbEditora);
        rbEditora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbEditora.setText("Editora");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisar por:");

        pesquisaOpcoes.add(rbCategoria);
        rbCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbCategoria.setText("Categoria");

        tableItens.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tableItens.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "ID", "Titulo", "Autor", "Editora", "Categoria", "Descrição", "Ano de publicação", "Disponível"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableItens);

        pesquisarBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pesquisarBtn.setText("Pesquisar");
        pesquisarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtnActionPerformed(evt);
            }
        });

        mostrarDisponiveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mostrarDisponiveis.setText("Mostrar apenas disponíveis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pesquisaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(mostrarDisponiveis)
                                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(pesquisarBtn))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(rbId)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rbTitulo)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rbAutor)))
                                                .addGap(18, 18, 18)
                                                .addComponent(rbEditora)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbCategoria)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(pesquisaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbId)
                                        .addComponent(rbTitulo)
                                        .addComponent(rbAutor)
                                        .addComponent(rbEditora)
                                        .addComponent(jLabel2)
                                        .addComponent(rbCategoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarDisponiveis)
                                .addGap(19, 19, 19)
                                .addComponent(pesquisarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private List<Item> pesquisarItens(String sql) {
        ItemDAO dao;
        List<Item> itens = null;

        try {
            dao = new ItemDAO();
            itens = dao.listItems(sql);
            dao.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return itens;
    }

    private void pesquisarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisarBtnActionPerformed
        String sql = "";
        DefaultTableModel table = (DefaultTableModel) tableItens.getModel();
        table.setNumRows(0);

        if (rbId.isSelected()) {
            sql = "SELECT * from item WHERE id=" + pesquisaInput.getText();
        } else if (rbTitulo.isSelected()) {
            sql = "SELECT * from item WHERE titulo LIKE '%" + pesquisaInput.getText() + "%'";
        } else if (rbAutor.isSelected()) {
            sql = "SELECT * from item WHERE autor LIKE '%" + pesquisaInput.getText() + "%'";
        } else if (rbEditora.isSelected()) {
            sql = "SELECT * from item WHERE editora LIKE '%" + pesquisaInput.getText() + "%'";
        } else if (rbCategoria.isSelected()) {
            sql = "SELECT * from item WHERE categoria LIKE '%" + pesquisaInput.getText() + "%'";
        }

        if (mostrarDisponiveis.isSelected()) {
            sql = sql + " and disponivel=true";
        }

        List<Item> itens = pesquisarItens(sql);
        String disponivel;

        for (Item item : itens) {
            disponivel = item.getIsAvailable() ? "Sim" : "Não";
            Object[] itemData = { item.getId(), item.getTitle(), item.getAuthor(), item.getPublisher(),
                    item.getKind(), item.getDescription(), item.getPublicationYear(), disponivel };
            table.addRow(itemData);
        }

    }// GEN-LAST:event_pesquisarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mostrarDisponiveis;
    private javax.swing.JTextField pesquisaInput;
    private javax.swing.ButtonGroup pesquisaOpcoes;
    private javax.swing.JButton pesquisarBtn;
    private javax.swing.JRadioButton rbAutor;
    private javax.swing.JRadioButton rbCategoria;
    private javax.swing.JRadioButton rbEditora;
    private javax.swing.JRadioButton rbId;
    private javax.swing.JRadioButton rbTitulo;
    private javax.swing.JTable tableItens;
    // End of variables declaration//GEN-END:variables
}
