/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.ViewUsuarios.ViewPesquisarUsuarios;

import javax.swing.JInternalFrame.JDesktopIcon;

import view.ViewAcervo.ViewCadAcervo;
import view.ViewAcervo.ViewEditarAcervo;
import view.ViewAcervo.ViewExcluirAcervo;
import view.ViewAcervo.ViewListarAcervo;
import view.ViewAcervo.ViewPesquisarAcervo;
import view.ViewClientes.CadCliente;
import view.ViewClientes.EditCliente;
import view.ViewClientes.ExcluirCliente;
import view.ViewClientes.ListarClientes;
import view.ViewClientes.PesquisarClientes;
import view.ViewEmprestimos.ViewDevoluçãoEmprestimo;
import view.ViewEmprestimos.ViewEstenderEmprestimo;
import view.ViewEmprestimos.ViewNovoEmprestimo;
import view.ViewEmprestimos.ViewPesquisarEmprestimo;
import view.ViewRelatorios.ViewEmprestimosPorPeriodo;
import view.ViewRelatorios.ViewHistoricoRelatorios;
import view.ViewUsuarios.ViewCadUsuarios;
import view.ViewUsuarios.ViewExcluirUsuarios;
import view.ViewUsuarios.ViewListarUsuarios;
import view.ViewUsuarios.ViewEditarUsuarios;

/**
 *
 * @author Pedro Santos
 */
public class ViewAdmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ViewAdmDashboard
     */
    public ViewAdmDashboard() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/book-stack-icon-256.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAcervo = new javax.swing.JMenu();
        cadAcervo = new javax.swing.JMenuItem();
        editarAcervo = new javax.swing.JMenuItem();
        excluirAcervo = new javax.swing.JMenuItem();
        pesquisarAcervo = new javax.swing.JMenuItem();
        listarAcervo = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenu();
        cadClientes = new javax.swing.JMenuItem();
        editarClientes = new javax.swing.JMenuItem();
        excluirClientes = new javax.swing.JMenuItem();
        pesquisarClientes = new javax.swing.JMenuItem();
        listarClientes = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenu();
        cadUsuarios = new javax.swing.JMenuItem();
        editarUsuarios = new javax.swing.JMenuItem();
        excluirUsuarios = new javax.swing.JMenuItem();
        pesquisarUsuarios = new javax.swing.JMenuItem();
        listarUsuarios = new javax.swing.JMenuItem();
        mnEmprestimos = new javax.swing.JMenu();
        novoEmprestimo = new javax.swing.JMenuItem();
        estenderEmprestimo = new javax.swing.JMenuItem();
        devolucaoEmprestimo = new javax.swing.JMenuItem();
        pesquisarEmprestimo = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        histRelatorios = new javax.swing.JMenuItem();
        histRelatorios1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard (ADM)");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-stack-icon-256.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(799, 799, 799))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        mnAcervo.setText("Acervo");

        cadAcervo.setText("Cadastrar");
        cadAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAcervoActionPerformed(evt);
            }
        });
        mnAcervo.add(cadAcervo);

        editarAcervo.setText("Editar");
        editarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAcervoActionPerformed(evt);
            }
        });
        mnAcervo.add(editarAcervo);

        excluirAcervo.setText("Excluir");
        excluirAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAcervoActionPerformed(evt);
            }
        });
        mnAcervo.add(excluirAcervo);

        pesquisarAcervo.setText("Pesquisar");
        pesquisarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAcervoActionPerformed(evt);
            }
        });
        mnAcervo.add(pesquisarAcervo);

        listarAcervo.setText("Listar");
        listarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAcervoActionPerformed(evt);
            }
        });
        mnAcervo.add(listarAcervo);

        jMenuBar1.add(mnAcervo);

        mnClientes.setText("Clientes");

        cadClientes.setText("Cadastrar");
        cadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClientesActionPerformed(evt);
            }
        });
        mnClientes.add(cadClientes);

        editarClientes.setText("Editar");
        editarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClientesActionPerformed(evt);
            }
        });
        mnClientes.add(editarClientes);

        excluirClientes.setText("Excluir");
        excluirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClientesActionPerformed(evt);
            }
        });
        mnClientes.add(excluirClientes);

        pesquisarClientes.setText("Pesquisar");
        pesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClientesActionPerformed(evt);
            }
        });
        mnClientes.add(pesquisarClientes);

        listarClientes.setText("Listar");
        listarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarClientesActionPerformed(evt);
            }
        });
        mnClientes.add(listarClientes);

        jMenuBar1.add(mnClientes);

        mnUsuarios.setText("Usuários");

        cadUsuarios.setText("Cadastrar");
        cadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadUsuariosActionPerformed(evt);
            }
        });
        mnUsuarios.add(cadUsuarios);

        editarUsuarios.setText("Editar");
        editarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuariosActionPerformed(evt);
            }
        });
        mnUsuarios.add(editarUsuarios);

        excluirUsuarios.setText("Excluir");
        excluirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuariosActionPerformed(evt);
            }
        });
        mnUsuarios.add(excluirUsuarios);

        pesquisarUsuarios.setText("Pesquisar");
        pesquisarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarUsuariosActionPerformed(evt);
            }
        });
        mnUsuarios.add(pesquisarUsuarios);

        listarUsuarios.setText("Listar");
        listarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUsuariosActionPerformed(evt);
            }
        });
        mnUsuarios.add(listarUsuarios);

        jMenuBar1.add(mnUsuarios);

        mnEmprestimos.setText("Empréstimos");

        novoEmprestimo.setText("Novo");
        novoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEmprestimoActionPerformed(evt);
            }
        });
        mnEmprestimos.add(novoEmprestimo);

        estenderEmprestimo.setText("Estender");
        estenderEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estenderEmprestimoActionPerformed(evt);
            }
        });
        mnEmprestimos.add(estenderEmprestimo);

        devolucaoEmprestimo.setText("Devolução");
        devolucaoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucaoEmprestimoActionPerformed(evt);
            }
        });
        mnEmprestimos.add(devolucaoEmprestimo);

        pesquisarEmprestimo.setText("Pesquisar");
        pesquisarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarEmprestimoActionPerformed(evt);
            }
        });
        mnEmprestimos.add(pesquisarEmprestimo);

        jMenuBar1.add(mnEmprestimos);

        mnRelatorios.setText("Relatórios");

        histRelatorios.setText("Histórico de Empréstimos");
        histRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histRelatoriosActionPerformed(evt);
            }
        });
        mnRelatorios.add(histRelatorios);

        histRelatorios1.setText("Ver Empréstimos por Período");
        histRelatorios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histRelatorios1ActionPerformed(evt);
            }
        });
        mnRelatorios.add(histRelatorios1);

        jMenuBar1.add(mnRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void histRelatorios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histRelatorios1ActionPerformed
       ViewEmprestimosPorPeriodo empPeriodo = new ViewEmprestimosPorPeriodo();
       jDesktopPane1.add(empPeriodo);
       empPeriodo.setVisible(true);
    }//GEN-LAST:event_histRelatorios1ActionPerformed

    private void pesquisarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarEmprestimoActionPerformed
        ViewPesquisarEmprestimo pesquisarEmprestimo = new ViewPesquisarEmprestimo();
        jDesktopPane1.add(pesquisarEmprestimo);
        pesquisarEmprestimo.setVisible(true);
    }//GEN-LAST:event_pesquisarEmprestimoActionPerformed

    private void histRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_histRelatoriosActionPerformed

        ViewHistoricoRelatorios historicoRelatorios = new ViewHistoricoRelatorios();
        jDesktopPane1.add(historicoRelatorios);
        historicoRelatorios.setVisible(true);
    }// GEN-LAST:event_histRelatoriosActionPerformed

    private void cadClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadClientesActionPerformed
        CadCliente cadCliente = new CadCliente();
        jDesktopPane1.add(cadCliente);
        cadCliente.setVisible(true);
    }// GEN-LAST:event_cadClientesActionPerformed

    private void editarClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarClientesActionPerformed
        EditCliente editCliente = new EditCliente();
        jDesktopPane1.add(editCliente);
        editCliente.setVisible(true);
    }// GEN-LAST:event_editarClientesActionPerformed

    private void excluirClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirClientesActionPerformed
        ExcluirCliente excluirCliente = new ExcluirCliente();
        jDesktopPane1.add(excluirCliente);
        excluirCliente.setVisible(true);
    }// GEN-LAST:event_excluirClientesActionPerformed

    private void pesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisarClientesActionPerformed
        PesquisarClientes pesquisarClientes = new PesquisarClientes();
        jDesktopPane1.add(pesquisarClientes);
        pesquisarClientes.setVisible(true);
    }// GEN-LAST:event_pesquisarClientesActionPerformed

    private void listarClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listarClientesActionPerformed
        ListarClientes listarClientes = new ListarClientes();
        jDesktopPane1.add(listarClientes);
        listarClientes.setVisible(true);
    }// GEN-LAST:event_listarClientesActionPerformed

    private void devolucaoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_devolucaoEmprestimoActionPerformed
        ViewDevoluçãoEmprestimo devolucaoEmprestimo = new ViewDevoluçãoEmprestimo();
        jDesktopPane1.add(devolucaoEmprestimo);
        devolucaoEmprestimo.setVisible(true);
    }// GEN-LAST:event_devolucaoEmprestimoActionPerformed

    private void estenderEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estenderEmprestimoActionPerformed
        ViewEstenderEmprestimo estenderEmprestimo = new ViewEstenderEmprestimo();
        jDesktopPane1.add(estenderEmprestimo);
        estenderEmprestimo.setVisible(true);
    }// GEN-LAST:event_estenderEmprestimoActionPerformed

    private void novoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_novoEmprestimoActionPerformed
        ViewNovoEmprestimo novoEmprestimo = new ViewNovoEmprestimo();
        jDesktopPane1.add(novoEmprestimo);
        novoEmprestimo.setVisible(true);
    }// GEN-LAST:event_novoEmprestimoActionPerformed

    private void cadAcervoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadAcervoActionPerformed
        ViewCadAcervo cadAcervo = new ViewCadAcervo();
        jDesktopPane1.add(cadAcervo);
        cadAcervo.setVisible(true);
    }// GEN-LAST:event_cadAcervoActionPerformed

    private void editarAcervoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarAcervoActionPerformed
        ViewEditarAcervo editarAcervo = new ViewEditarAcervo();
        jDesktopPane1.add(editarAcervo);
        editarAcervo.setVisible(true);
    }// GEN-LAST:event_editarAcervoActionPerformed

    private void excluirAcervoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirAcervoActionPerformed
        ViewExcluirAcervo excluirAcervo = new ViewExcluirAcervo();
        jDesktopPane1.add(excluirAcervo);
        excluirAcervo.setVisible(true);
    }// GEN-LAST:event_excluirAcervoActionPerformed

    private void pesquisarAcervoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisarAcervoActionPerformed
        ViewPesquisarAcervo pesquisarAcervo = new ViewPesquisarAcervo();
        jDesktopPane1.add(pesquisarAcervo);
        pesquisarAcervo.setVisible(true);
    }// GEN-LAST:event_pesquisarAcervoActionPerformed

    private void listarAcervoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listarAcervoActionPerformed
        ViewListarAcervo listarAcervo = new ViewListarAcervo();
        jDesktopPane1.add(listarAcervo);
        listarAcervo.setVisible(true);
    }// GEN-LAST:event_listarAcervoActionPerformed

    private void cadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadUsuariosActionPerformed
        ViewCadUsuarios cadUsuarios = new ViewCadUsuarios();
        jDesktopPane1.add(cadUsuarios);
        cadUsuarios.setVisible(true);
    }// GEN-LAST:event_cadUsuariosActionPerformed

    private void editarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarUsuariosActionPerformed
        ViewEditarUsuarios editarUsuarios = new ViewEditarUsuarios();
        jDesktopPane1.add(editarUsuarios);
        editarUsuarios.setVisible(true);
    }// GEN-LAST:event_editarUsuariosActionPerformed

    private void excluirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirUsuariosActionPerformed
        ViewExcluirUsuarios excluirUsuarios = new ViewExcluirUsuarios();
        jDesktopPane1.add(excluirUsuarios);
        excluirUsuarios.setVisible(true);
    }// GEN-LAST:event_excluirUsuariosActionPerformed

    private void pesquisarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisarUsuariosActionPerformed
        ViewPesquisarUsuarios pesquisarUsuarios = new ViewPesquisarUsuarios();
        jDesktopPane1.add(pesquisarUsuarios);
        pesquisarUsuarios.setVisible(true);
    }// GEN-LAST:event_pesquisarUsuariosActionPerformed

    private void listarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listarUsuariosActionPerformed
        ViewListarUsuarios listarUsuarios = new ViewListarUsuarios();
        jDesktopPane1.add(listarUsuarios);
        listarUsuarios.setVisible(true);
    }// GEN-LAST:event_listarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadAcervo;
    private javax.swing.JMenuItem cadClientes;
    private javax.swing.JMenuItem cadUsuarios;
    private javax.swing.JMenuItem devolucaoEmprestimo;
    private javax.swing.JMenuItem editarAcervo;
    private javax.swing.JMenuItem editarClientes;
    private javax.swing.JMenuItem editarUsuarios;
    private javax.swing.JMenuItem estenderEmprestimo;
    private javax.swing.JMenuItem excluirAcervo;
    private javax.swing.JMenuItem excluirClientes;
    private javax.swing.JMenuItem excluirUsuarios;
    private javax.swing.JMenuItem histRelatorios;
    private javax.swing.JMenuItem histRelatorios1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem listarAcervo;
    private javax.swing.JMenuItem listarClientes;
    private javax.swing.JMenuItem listarUsuarios;
    private javax.swing.JMenu mnAcervo;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnEmprestimos;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnUsuarios;
    private javax.swing.JMenuItem novoEmprestimo;
    private javax.swing.JMenuItem pesquisarAcervo;
    private javax.swing.JMenuItem pesquisarClientes;
    private javax.swing.JMenuItem pesquisarEmprestimo;
    private javax.swing.JMenuItem pesquisarUsuarios;
    // End of variables declaration//GEN-END:variables
}
